apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-operator-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: demo-operator-frontend
  template:
    metadata:
      labels:
        name: demo-operator-frontend
    spec:
      serviceAccountName: demo-operator-frontend
      containers:
        - name: demo-operator-frontend
          # Replace this with the built image name
          image: localhost:5000/demo-operator-frontend:v0.0.1
          command:
          - demo-operator-frontend
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "demo-operator-frontend"
